---

- name: install dependencies
  apt:
    name: '{{ item }}'
    state: 'present'
    update_cache: yes
    cache_valid_time: 3600
  with_items: gogs_dependency_pkgs


- name: create user git
  user:
    name: '{{ gogs_user }}'
    comment: 'Gogs Git Service'
    home: '{{ gogs_user_home }}'
    shell: '/bin/bash'

- name: get binary
  get_url:
    url: '{{ gogs_binary_url }}/{{ gogs_version }}'
    dest: '{{ gogs_user_home }}/gogs.zip'
    owner: '{{ gogs_user }}'
    group: '{{ gogs_user }}'

- name: unzip binary zip
  sudo_user: '{{ gogs_user }}'
  unarchive:
    src: '{{ gogs_user_home}}/gogs.zip'
    dest: '{{ gogs_user_home }}/'
    creates: '{{ gogs_user_home }}/gogs'
    copy: no
    owner:  '{{ gogs_user }}'
    group: '{{ gogs_user }}'

- name: set custom conf folder
  file:
    state: directory
    recurse: yes
    path: '{{ gogs_user_home }}/gogs/custom/conf'
    owner: '{{ gogs_user }}'
    group: '{{ gogs_user }}'
    mode: 0755

- name: create Gogs log folder.
  file:
    path: '{{ gogs_user_home }}/gogs/log'
    state: 'directory'
    owner: '{{ gogs_user }}'
    group: '{{ gogs_user }}'
    mode: 0755

- name: configure app.ini
  template:
    src: 'app.ini.j2'
    dest: '{{ gogs_user_home }}/gogs/custom/conf/app.ini'
    owner: '{{ gogs_user }}'
    group: '{{ gogs_user }}'

- name: make binary executable
  file:
    path: '{{ gogs_user_home }}/gogs/gogs'
    owner: '{{ gogs_user }}'
    group: '{{ gogs_user }}'
    mode: 0755
  notify: restart_gogs

- name: debug gogs
  shell: 'ls -al {{ gogs_user_home }}/gogs'
  register: debug_gogs

- name: debug gogs/scripts
  shell: 'ls -al {{ gogs_user_home }}/gogs/scripts'
  register: debug_scripts

- debug: var=debug_gogs.stdout

- debug: var=debug_scripts.stdout



- name: copy the init script
  template:
    src: gogs-server.j2
    dest: /etc/init.d/gogs-server
    owner: root
    group: root
    mode: '0755'
  notify: restart_gogs